# Generated by Django 5.1 on 2024-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppoinmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=20)),
                ('selected_date', models.DateField()),
                ('selected_time', models.TimeField()),
                ('services', models.CharField(blank=True, choices=[('scheduled-services', 'Scheduled Services'), ('ac-services', 'AC Services'), ('cleaning-detailing', 'Cleaning & Detailing'), ('lights-fitments', 'Lights Fitments'), ('denting-painting', 'Denting & Painting'), ('insurance-services', 'Insurance Services'), ('custom-repair', 'Custom Repair'), ('batteries', 'Batteries'), ('tyres', 'Tyres'), ('detailing-services', 'Detailing Services'), ('windshields-glass', 'Windshields & Glass'), ('other', 'Other')], max_length=255)),
            ],
        ),
    ]
