# Generated by Django 5.1 on 2024-09-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_appointment_delete_appoinmentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
