# Generated by Django 5.1 on 2024-09-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_image_alter_appointment_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
