# Generated by Django 5.1 on 2024-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Gallary_images/'),
        ),
    ]
