# Generated by Django 5.1 on 2024-09-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_rename_src_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
