# Generated by Django 5.1 on 2024-09-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_imagecategory_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
