# Generated by Django 5.1 on 2024-09-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
